### ISSUE TITLE
Align

### ISSUE THREAD

**Issue by rezoner** [rezoner/CanvasQuery#35]
Not really sure how would it work without CPU overhead but I think

```
this.layer.align(0.5, 0.5)
```

would be awesome.

It would affect drawImage, drawRegion, paths  auto-magically centering them upon desired point.

**Comment by rezoner** [comment]
In particualar I am nervously looking to replace the pattern that happens 24/7 in my code:

```javascript
app.layer.save();
app.layer.translate(x, y);
app.layer.rotate(rotation);
app.layer.scale(scale, scale);
app.layer.drawImage(image, -image.width / 2, -image.height /2);
app.layer.restore();
```

**Comment by rezoner** [comment]
First iteration - introducing `align`:

```javascript
app.layer.align(x, y, 0.5, 0.5);
app.layer.rotate(rotation);
app.layer.scale(scale, scale);
app.layer.drawImage(image, 0, 0);
app.layer.restore();
```

**Comment by rezoner** [comment]
How about:

`align`

```javascript
app.layer.save()
  .translate(x, y)
  .align(0.5, 0.5)
  .rotate(0.5)
  .scale(1.0, 1.0)
  .drawImage(image, 0, 0)
  .restore();

`stars` = `save`, `translate`, `align`, `rotate`, `scale`

app.layer
  .stars(100, 100, 0.5, 0.5, 0.4, 1.0)
  .drawImage(image, 0, 0)
  .restore();

**Comment by feiss** [comment]
Nice, and undefined parameters could default to (0,0,0,0,0,1), so you could do stars(100,100) just to translate, stars(100,100,0.5,0.5,0.4) to rotate around center but not scale, etc..

clean and handy, do you like it?

**Comment by rezoner** [comment]
Yesh I do.

I guess `align` in the end would make more sense as you usually want to have just 0.5, 0.5

But then STARS makes it easy to remember the arguments order.

**Comment by feiss** [comment]
And you can sell it well: "Now with a brand new *STARS* operator!"

Powerful shit.

**Comment by rezoner** [comment]
Pushed online

https://twitter.com/rezoner/status/562921309890703360
